// Trips
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const FETCH_POLYLINE_SUCCESS = 'FETCH_POLYLINE_SUCCESS';
export const FETCH_START_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const FETCH_END_SUCCESS = 'FETCH_TRIP_SUCCESS';
